services:
  migrate:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - ./NodeGuard:/app

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./NodeGuard:/app
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

  worker:
    build: .
    command: python manage.py run_huey
    volumes:
      - ./NodeGuard:/app
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
