# Generated by Django 6.1 on 2026-08-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0002_target_alter_scan_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scan",
            name="wordlist",
            field=models.FileField(blank=True, null=True, upload_to="wordlists/"),
        ),
    ]
