# Generated by Django 6.1 on 2026-08-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0003_scan_options_scan_wordlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("scanner_name", models.CharField(max_length=100)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
