# Generated by Django 6.1 on 2026-08-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanners", "0005_builtin_security_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
